### ISSUE TITLE
Authentication succeeds but unable to send any requests

### ISSUE THREAD

**Issue by 4a454646** [88/mojang-api-docs#18]
Hello,
Thank you for the detailed documentation. Unfortunately, I am still struggling. I have successfully authenticated my Mojang account and received the accessToken via these [instructions](https://mojang-api-docs.netlify.app/authentication/mojang.html).

I then plugged the accessToken into a base64 decoder and got the yggdrasil token from the extracted decoded json via these instructions [here](https://mojang-api-docs.netlify.app/authentication/bearers.html).

However, I am now trying to access anything that requires authorization—for example, the security questions.
In Python, I use a get request of `r = requests.get(url = URL, headers={"Authorization": "Bearer <yggtToken>"})`, where the yggtToken is the one taken from the decoded json. 

The problem is that I am still getting "Unauthorized", with it saying that the request requires user authentication (basically saying I got my bearer token wrong). Can anyone help me out?

**Comment by lucky-swede** [comment]
The JWT is what you want to pass to the API in the header. Not the decoded yggdrasil token. Hope that helps.

**Comment by 4a454646** [comment]
I have tried passing in the entire JWT token (the one with the two periods) but no luck. I also tried passing in each segment individually, but same result.

**Comment by lucky-swede** [comment]
And you made sure to place "`Bearer `" before the token?

**Comment by lucky-swede** [comment]
Oh, this is for Mojang accounts? All API endpoints for Mojang accounts no longer work. You will need to migrate to Microsoft to get a valid token.

**Comment by 4a454646** [comment]
Yes, this is for Mojang accounts. I think that is the problem.
