### ISSUE TITLE
Fetch sale statistics : Endpoint still available ?

### ISSUE THREAD

**Issue by Distractic** [88/mojang-api-docs#19]
This endpoint at the page https://mojang-api-docs.netlify.app/no-auth/sale-stats.html is still functional ?

I have the following error : 

```json
{"error":"Unsupported Media Type","errorMessage":"The server is refusing to service the request because the entity of the request is in a format not supported by the requested resource for the requested method"}
```

Body and headers put, but nothing seems fix that

**Comment by lucky-swede** [comment]
This endpoint was removed, and this update will be added in the next update which will take place in the next while. See the project I made about updating the docs. https://github.com/88/mojang-api-docs/projects/1

**Comment by lucky-swede** [comment]
Fixed this.
