### ISSUE TITLE
Username availability (accurate) : Response changed

### ISSUE THREAD

**Issue by Distractic** [88/mojang-api-docs#20]
The response from the API has changed

When a username is not availabled (username already used) with the link https://account.mojang.com/available/minecraft/Notch  : 
- status : 200 OK
- response : 
```json
{"name":"Notch","id":"069a79f444e94726a5befca90e38aaf5"}
```

When a username is availabled (username not used) with the link https://account.mojang.com/available/minecraft/ezffnezfjbezfezf  : 
- status : 204 No Content
- response : no body

**Comment by bigfoot547** [comment]
See the header on this page: https://mojang-api-docs.netlify.app/no-auth/username-availability-partially-accurate.html

The endpoint now redirects to an unrelated endpoint (documented, although I grant it says "UUID to username" when it should say "Username to UUID").

**Comment by lucky-swede** [comment]
This endpoint was deprecated already in the docs but there is the type issue which will be fixed in the next update. Thanks for pointing this out.

**Comment by lucky-swede** [comment]
Fixed this.
