### ISSUE TITLE
Giftcode Redemption

### ISSUE THREAD

**Issue by Hycord** [88/mojang-api-docs#4]
How do you redeem a giftcode with a username at the same time? do I need to use the giftcode on an account then change the acocunt's username..?

**Comment by wh-at** [comment]
First, redeem the giftcode on a MSA. Then, do NOT set a profile name. Once it's time to snipe, fire off these requests while authenticated: https://mojang-api-docs.netlify.app/needs-auth/create-profile.html

**Comment by drainer** [comment]
Closing this as it has been almost 30 days of it being open.
