### ISSUE TITLE
Multiple usernames -> uuids is now disabled.

### ISSUE THREAD

**Issue by surprise** [88/mojang-api-docs#5]
https://i.ibb.co/k5PKFd4/Insomnia-OBI7-Tg4zgk.png

**Comment by drainer** [comment]
Hi, when I get to my PC next I’ll put out a quick fix for this.

Currently working on a large rewrite and retest of all the API endpoints as well as new docs for logging in with MSA, please bear with me! Those changes can be seen in the other branch of this repo or at https://88.github.io/mojang-api-docs/book/. 

I’ll keep this issue open until this is fixed, which should be in a few hours.

**Comment by drainer** [comment]
Endpoint is in fact fixed now, so I don't think I'll be including this anymore
