### ISSUE TITLE
[Documentation] 404 Status for Change-name

### ISSUE THREAD

**Issue by wwhtrbbtt** [88/mojang-api-docs#6]
Hi!
I love the project. I think I found something that isn't documented yet: When you make a PUT request to https://api.minecraftservices.com/minecraft/profile/name/:username using a microsoft account that doesn't own a copy of minecraft, you will get a 404 response.

Hope I could help

**Comment by drainer** [comment]
Will add this when I make the next big update. Currently really busy and can't add each thing individually but I have a queue to get through. Should hopefully be done by end of May. Thank you for your contribution!

Keeping this open until I add this and push it to master.

**Comment by drainer** [comment]
Hey there! This has been finally added. I'm so sorry for the wait - had a lot of things going on outside of Minecraft and whatnot.

Thanks again for your contribution, your name has been added to the README and index page!
